# Generated by Django 4.2.7 on 2023-11-06 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveBigIntegerField()),
                ('sex', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_type', models.CharField(max_length=255)),
                ('time_from_treatment_start', models.PositiveBigIntegerField()),
                ('response', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True)),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teiko_takehome.condition')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teiko_takehome.project')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teiko_takehome.subject')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teiko_takehome.treatment')),
            ],
        ),
        migrations.CreateModel(
            name='CellCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_cell', models.PositiveBigIntegerField()),
                ('cd8_t_cell', models.PositiveBigIntegerField()),
                ('cd4_t_cell', models.PositiveBigIntegerField()),
                ('nk_cell', models.PositiveBigIntegerField()),
                ('monocyte', models.PositiveBigIntegerField()),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cell_counts', to='teiko_takehome.sample')),
            ],
        ),
    ]
